### ISSUE TITLE
Should re-organizing the features supported on real TV devices

### ISSUE THREAD

**Issue by rookiejava** [Samsung/Tizen.TV.UIControls#26]
Some APIs (such as MediaView) aren't supported on real TV devices.  That meas it cannot be used. Therefore, we should select and provide only the features avaialb on real TV devices.

**Comment by JoonghyunCho** [comment]
A few changes have been prepared (https://github.com/Samsung/Tizen.TV.UIControls/pull/29)
- `MediaView` is changed to an abstract class to prevent creating.
- Related samples are deleted.
- MediaPlayer guide is modified.
