### ISSUE TITLE
RTSP Streaming support

### ISSUE THREAD

**Issue by decv86** [Samsung/Tizen.TV.UIControls#51]
Hi!
RTSP Streaming support?
Tnx!

**Comment by rookiejava** [comment]
Yes, for RTSP streaming, URI should start with "rtsp://.

For examples, 
```cs
player.Source = MediaSource.FromUri(new System.Uri("rtsp://xxx.yyy"));
```

**Comment by decv86** [comment]
Its no work in emulator Samsung 5.0:
player.Source = MediaSource.FromUri(new System.Uri("rtsp://192.168.8.39:7447/eSXE5QPd7qumFu51"));
player.Start();

**Comment by myroot** [comment]
Did you set internet privilege?
`http://tizen.org/privilege/internet`
