### ISSUE TITLE
OverlayMediaView not update player geometry directly

### ISSUE THREAD

**Issue by AliDem** [Samsung/Tizen.TV.UIControls#56]
Hello,
I use videoview like your sample(TestOverlayView) in a absolutLayout, init videoview Layout Bounds is (960,40,960,540)
I would like resize my videoview following a keyDown  and set Layout to this rectangle (0,0,1920,1080), and vice versa.

Layout Method:
On first press, layout is resized to full sreen mode (ok), but player not yet (keep same size),
On second press, layout is resized to small screen mode, but player take previous size (become full screen). Not synchronous.

LayoutTo Method:
Work (videoview and player changes) but layout bounds are'nt respect rectangle dimension.

I'm using VS 2019 / Xamarin.forms 4.4.0.991537 / Tizen 5.0 / Emulator TV 5.5 x86

Thank you

**Comment by myroot** [comment]
Could you share your app code?

**Comment by myroot** [comment]
I was identify this issue. I will try to fix it

**Comment by gamukeat** [comment]
Thank you, I solved by using creating an overlay view by implemeting MediaView,IVideoOutput

**Comment by myroot** [comment]
It was fixed, but if you want to fix at early you can update a geometry by update a value twice
For example
``` c#
            AbsoluteLayout.SetLayoutBounds(VideoView, new Rectangle(0, 0, 1920, 1080));
            AbsoluteLayout.SetLayoutBounds(VideoView, new Rectangle(0, 0, 1920, 1081));
```

**Comment by gamukeat** [comment]
Thank you, I will try.
