### ISSUE TITLE
Change active audio/subtitle in Player

### ISSUE THREAD

**Issue by AliDem** [Samsung/Tizen.TV.UIControls#58]
Hi,

Can we change audio/subtitle during playing?
Some content have more 1 subtitles or audios, and I would like to give to possibility to users to select and change it.

But I did'nt see those features in default Tizen.Multimedia.Player?

There are a solution?

**Comment by rookiejava** [comment]
Well, try this [one](https://samsung.github.io/TizenFX/latest/api/Tizen.Multimedia.Player.html#Tizen_Multimedia_Player_SetSubtitle_System_String_).
