### ISSUE TITLE
Dll refers a forbidden assembly directly - libevas.so

### ISSUE THREAD

**Issue by vitalii-smal** [Samsung/Tizen.TV.UIControls#79]
Hi,

I am developing Tizen .NET application on Xamarin Forms for TizenTV with target framework .NET Tizen 4.0. 

I’ve tried to use your TizenTV.UIControls NuGet package and it works great on emulator. But when I try to use it **on physical device** I experience next **error**:
`[FAIL] Tizen.TV.UIControls.Forms.dll refers a forbidden assembly directly - libevas.so. 1 :(` 

Take into account that I have already tried to use next versions of package: 1.0.0, 1.1.0 pre1, 1.1.0 pre2, 1.1.0 pre3. 

**Is it possible to fix this problem? 
If there exists a solution, will it match Samsung Apps TV Seller Office’s requirements in order to publish it later?** 

Who also has ever stuck with the same problem? As I know loading the library provided by TV product using DllImport is not supported. 

Best Regards,
Vitalii

**Comment by rookiejava** [comment]
Hi, thank you for reaching us!

Unfortunately, as guided in the FAQ [here](https://developer.samsung.com/tizen/Smart-TV/FAQ/FAQ.html), existing TV product doesn't allow DllImport for security reasons. However, if I know correctly, this restriction will be removed from the 2021 TV models with Tizen 6.5. 

For more information, it would be good to contact the Samsung Apps TV Seller Office.

**Comment by nicco** [comment]
Is it possible at all to use Xamarin Forms on a Samsung 2020 TV ?

**Comment by rookiejava** [comment]
> Is it possible at all to use Xamarin Forms on a Samsung 2020 TV ?

Yes.  

https://developer.samsung.com/tizen/Smart-TV/Quickstarts/Creating-an-application.html
